version: '2'
services:
  raspberry-pint:
    container_name: rapberry-web
    build:
      context: ./
      dockerfile: ./docker/Dockerfile_web
    ports:
      - "8093:80"
    volumes:
      - ./www:/var/www/html
    links:
      - database:database
    restart: unless-stopped
  database:
    container_name: pints-database
    restart: unless-stopped
    image: mysql:5.6
    ports:
      - "3408:3306"
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: raspberrypints
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - ./mysql/data:/var/lib/mysql
