FROM php:5.6-apache

RUN apt-get update && apt-get -y install libssl-dev mysql-client mysql-server

#Install dependencies
RUN docker-php-ext-install mysql && docker-php-ext-enable mysql
RUN docker-php-ext-install mysqli && docker-php-ext-enable mysqli
RUN docker-php-ext-install mbstring && docker-php-ext-enable mbstring

RUN usermod -u 1000 www-data && groupmod -g 1000 www-data

# Apache enable rewrite
RUN a2enmod rewrite
